export const GET_TRADES_SUCCESS = "GET_TRADES_SUCCESS";
export const GET_TRADES_LOADING = "GET_TRADES_LOADING";
export const GET_TRADES_FAIL = "GET_TRADES_FAIL";

export const GET_CURRENCY_PAIRS_SUCCESS = "GET_CURRENCY_PAIRS_SUCCESS";
export const GET_CURRENCY_PAIRS_LOADING = "GET_CURRENCY_PAIRS_LOADING";
export const GET_CURRENCY_PAIRS_FAIL = "GET_CURRENCY_PAIRS_FAIL";
